CREATE TABLE IF NOT EXISTS `users` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`username` VARCHAR(320) NOT NULL,
	`email` VARCHAR(320) NOT NULL,
	`password_hash` BINARY(60) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `username_email` (`username`, `email`)
) ENGINE=InnoDB;	
